version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover tests

      - echo "Zipping Lambda code..."
      - zip -r function.zip src

      - echo "Uploading function.zip to a fixed S3 path..."
      - aws s3 cp function.zip s3://serverless-ecommerce-static-artifacts/fixed-path/function.zip
artifacts:
  files: []
