version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - mkdir -p build
      - zip build/function.zip src/products/*.py
      - cp infra/template.yaml build/
artifacts:
  files:
    - build/function.zip
    - build/template.yaml
  base-directory: build
