version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip function.zip src/products/*.py
artifacts:
  files:
    - function.zip
    - infra/template.yaml
