version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - echo "Running pre-build steps..."
  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover tests
      - echo "Zipping Lambda code..."
      - cd src
      - zip -r ../function.zip .
      - cd ..
      - echo "Uploading function.zip and template.yaml to fixed S3 path..."
      - aws s3 cp function.zip s3://serverless-ecommerce-static-artifacts/fixed-path/function.zip
      - aws s3 cp template.yaml s3://serverless-ecommerce-static-artifacts/fixed-path/template.yaml
  post_build:
    commands:
      - echo "Build and tests completed successfully."

artifacts:
  files: []
