version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - mkdir -p build  # Create a known folder for artifacts
      - zip build/function.zip src/products/*.py
      - cp infra/template.yaml build/
artifacts:
  files:
    - build/*
  base-directory: build  # Ensures all artifacts are placed under the 'build' directory
