---
- name: Configure AWS environment and Dev Tools
  hosts: all
  become: yes
  vars:
    aws_access_key_id: ""
    aws_secret_access_key: ""
    aws_region: "us-east-1"
    environment_name: "dev"
    dynamo_table_name: "Products"

  tasks:
    - name: Validate python3
      command: python3 --version
      changed_when: false

    - name: Validate pip3
      command: pip3 --version
      changed_when: false

    - name: Validate Ansible
      command: ansible --version
      changed_when: false

    - name: Validate AWS CLI
      command: aws --version
      changed_when: false

    - name: Make .aws folder
      file:
        path: ~/.aws
        state: directory
        mode: "0755"

    - name: Write AWS credentials
      copy:
        dest: ~/.aws/credentials
        mode: "0600"
        content: |
          [default]
          aws_access_key_id = {{ aws_access_key_id }}
          aws_secret_access_key = {{ aws_secret_access_key }}

    - name: Write AWS config
      copy:
        dest: ~/.aws/config
        mode: "0644"
        content: |
          [default]
          region = {{ aws_region }}

    - name: Try aws s3 ls
      command: aws s3 ls
      register: s3_output
      failed_when: s3_output.rc != 0
      changed_when: false

    - name: Debug s3 output
      debug:
        msg: "{{ s3_output.stdout_lines }}"

    - name: Add environment vars in /etc/environment
      lineinfile:
        path: /etc/environment
        line: "{{ item.key }}={{ item.value }}"
        create: yes
        state: present
      loop:
        - { key: ENVIRONMENT_NAME, value: "{{ environment_name }}" }
        - { key: DYNAMO_TABLE_NAME, value: "{{ dynamo_table_name }}" }
