AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless E-Commerce App

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

  LambdaArtifactBucket:
    Type: String
    Description: "Bucket for Lambda .zip"

  LambdaArtifactKey:
    Type: String
    Description: "Key for Lambda .zip"

Resources:
  ProductsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-ProductsLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ProductsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${EnvironmentName}-ProductsLambda"
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ProductsLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaArtifactBucket
        S3Key: !Ref LambdaArtifactKey
      Timeout: 10

Outputs:
  LambdaFunctionName:
    Value: !Ref ProductsLambdaFunction
    Description: "Name of the Lambda function"
