Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CreateProduct
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::211125598740:role/LambdaExecutionRole
      Code:
        S3Bucket: my-lambda-code-bucket
        S3Key: function.zip
